apiVersion: v1
kind: Service
metadata:
  name: {{cookiecutter.service_name}}
spec:
  selector:
    app: {{cookiecutter.deployment_name}}
  ports:
    - protocol: TCP
      port: {{cookiecutter.container_port}}
      targetPort: {{cookiecutter.target_port}}